# Makefile for building a test program on a
# host computer using the ordinary network stack
OBJS =  padProtoHost.o udpCommBSD.o padProto.o

padProtoHost: $(OBJS)
	$(CC)  -O2 -DBSDSOCKET -o $@ $^

%.o:%.c
	$(CC) -I. -c -O2 -DBSDSOCKET -o $@ $<

clean:
	$(RM) padProtoHost
	$(RM) $(OBJS)
